# Generated by Django 2.0.1 on 2018-01-15 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='start.dateTime')),
                ('start_zone', models.CharField(max_length=32, verbose_name='start.timeZone')),
                ('end_time', models.DateTimeField(verbose_name='end.dateTime')),
                ('end_zone', models.CharField(max_length=32, verbose_name='end.timeZone')),
                ('summary', models.TextField(verbose_name='summary')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cred', models.TextField(verbose_name='credentials')),
                ('email', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('logged_in', models.BooleanField()),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binaryclock.User'),
        ),
    ]
